#build stage
FROM golang:1.19-alpine AS builder
WORKDIR /app
COPY app.go .
RUN go build -o app app.go

#Run stage
FROM alpine:3.13
RUN apk update \
&& apk upgrade

WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 3002
CMD ["/app/app"]